---
- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks:
   - name: Copy war file
     copy:
      src: "/var/snap/jenkins/4865/workspace/AnsibleWebApp/target/AnsibleWebApp.war"
      dest: "/opt/tomcat/webapps/AnsibleWebApp.war"
      remote_src: no
   - name: restart tomcat
     systemd:
      name: tomcat
      state: restarted
